config/routes.rb
MyBaseApp::Application.routes.draw do

  devise_for :users
  match '/myprojects', :to => 'projects#index', :via => :get
  root :to => 'welcome#index'

  resources :projects

end

app/models/project.rb
class Project < ActiveRecord::Base

  validates :title, :description, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects  = Project.all
  end


  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to projects_path, :notice => 'Project has been created successfully'
    else
       render :action => :new
    end
  end


  private

  def project_params
    params.require(:project).permit(:title, :description)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def flash_message
    if flash[:notice]
      content_tag :div, flash[:notice],:class => 'alert alert-success'
    elsif flash[:error]
       content_tag :div, flash[:error], :class => 'alert alert-error'
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_carousal.html.erb
<!-- Carousel
================================================== -->
<div id="myCarousel" class="carousel slide">
  <div class="carousel-inner">
    <div class="item active">
      <img src="/assets/slide-01.jpg" alt="">
      <div class="container">
        <div class="carousel-caption">
          <h1>Add Project</h1>
          <p class="lead">Add project your team is working on.</p>
          <!--<a class="btn btn-large btn-primary" href="#">Sign up today</a>-->
        </div>
      </div>
    </div>
    <div class="item">
      <img src="/assets/slide-02.jpg" alt="">
      <div class="container">
        <div class="carousel-caption">
          <h1>Create Tickets.</h1>
          <p class="lead">Create tickets and easily manage them.</p>
          <!--<a class="btn btn-large btn-primary" href="#">Learn more</a>-->
        </div>
      </div>
    </div>
    <div class="item">
      <img src="/assets/slide-03.jpg" alt="">
      <div class="container">
        <div class="carousel-caption">
          <h1>Track Your Tickets</h1>
          <!--<p class="lead">Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>-->
          <!--<a class="btn btn-large btn-primary" href="#">Browse gallery</a>-->
        </div>
      </div>
    </div>
  </div>
  <a class="left carousel-control" href="#myCarousel" data-slide="prev">&lsaquo;</a>
  <a class="right carousel-control" href="#myCarousel" data-slide="next">&rsaquo;</a>
</div><!-- /.carousel -->

<script>
    !function ($) {
        $(function(){
            // carousel demo
            $('#myCarousel').carousel()
        })
    }(window.jQuery)
</script>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="brand" href="./index.html">Bootstrap</a>
      <div class="nav-collapse collapse">
        <ul class="nav">
          <li class="">
            <a href="./index.html">Home</a>
          </li>
          <li class="">
            <a href="./getting-started.html">Get started</a>
          </li>
          <li class="active">
            <a href="./scaffolding.html">Scaffolding</a>
          </li>
          <li class="">
            <a href="./base-css.html">Base CSS</a>
          </li>
          <li class="">
            <a href="./components.html">Components</a>
          </li>
          <li class="">
            <a href="./javascript.html">JavaScript</a>
          </li>
          <li class="">
            <a href="./customize.html">Customize</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Easy Project Management</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
  <script src="../assets/js/html5shiv.js"></script>
  <![endif]-->


</head>
<body>


<div id="wrapper">
  <header id='header'>
       <nav role='navigation' id='navigation'>
         <ul>
           <li>
            <a href="#">Help!</a>
           </li>
           <li>
             <a href="#">FAQ</a>
           </li>
         </ul>
       </nav>
  </header>
  <section id="side">
    <div class="inner">
      <p>
        Side bar Content
      </p>
    </div>
  </section>
  <section id="content">
    <div class="inner">
      <%= yield %>
    </div>
  </section>
  <footer id="footer">
    <div class="inner">
      <p>Footer Content</p>
    </div>
  </footer>
</div>
    <%#=render :partial => 'layouts/navbar'%>
    <%#=render :partial => 'layouts/carousal'%>

</body>
</html>

app/views/layouts/projects.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyBaseApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
  <script src="../assets/js/html5shiv.js"></script>
  <![endif]-->

  <!-- Fav and touch icons -->
  <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
  <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
  <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
  <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
  <link rel="shortcut icon" href="../assets/ico/favicon.png">

</head>
<body data-spy="scroll" data-target=".bs-docs-sidebar" data-twttr-rendered="true">
<%=render :partial => 'layouts/navbar'%>

<header class='jumbotron subhead' id='overview'>
  <div class="container">
    <h2>Friendly Project Management</h2>
    <p class="lead"></p>
  </div>
</header>

<div class='container'>

<%= yield %>
</div>

</body>
</html>

app/views/projects/index.html.erb
<div class='main_container'>
    <div class="row">
      <div class="span9">

          <% if @projects.empty? %>

            <div class="alert alert-danger bs-alert-old-docs">
              <strong>No Projects Found!</strong>
            </div>

            <div class='top-buffer'>
              <p>
                <%=link_to 'Create One', new_project_path, :class=>'btn btn-large btn-primary'%>
              </p>
            </div>

         <% else %>
            <div class='top-buffer'>
             <%=flash_message%>
            </div>
          <% end %>

        <!--<div class="row">
          <div class="span6">Level 2</div>
          <div class="span3">Level 2</div>
        </div>-->

      </div>
    </div>
</div>

app/views/projects/new.html.erb
<div class='row top-buffer'>
  <div class='span7'>

    <%=form_for @project, :class =>'bs-docs-example form-horizontal ' do |f|%>

        <div class="control-group">
          <%=f.label 'Write One Liner', :class => 'control-label', :for => 'inputEmail'%>
          <div class='controls'>
            <%=f.text_field :title%>
            <span class='has-error'><%=f.object.errors[:title][0] if f.object.errors[:title] %></span>
          </div>
        </div>

        <div class="control-group">
          <%=f.label 'Write Short description', :class => 'control-label', :for => 'inputDescription'%>
          <div class='controls'>
            <%=f.text_area :description, :rows => 8%>
            <span class='has-error'><%=f.object.errors[:description][0] if f.object.errors[:description]%></span>
          </div>
        </div>

        <div class='control-group'>
          <%=f.submit 'Create'%>
        </div>

    <% end %>
</div>
</div>

app/views/welcome/index.html.erb
<p>
  <h1 class='big-heading'>Manage Your Project Easily</h1>
</p>
<p>
  <%=link_to 'Click Here To Sign Up', new_user_registration_path %>
</p>